# .github/workflows/linux-build.yml
name: Linux Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build for Linux
        run: |
          export GOOS=linux
          export GOARCH=amd64
          go build -o bin/linux/tiny-proxy src/cmd/main.go

      - name: Upload Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: bin/linux/tiny-proxy
